version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    volumes:
      - ./e-commerce.sql:/docker-entrypoint-initdb.d/e-commerce.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  back:
    build: docker
    container_name: backend
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev
  
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
    depends_on:
      - back
    networks:
      - dev

networks:
  dev:

